### ISSUE TITLE
Add Mastodon social icon to Footer + Add updated Twitter icon to blog

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/okturtles.org#62]
### Problem

We need to link to [our decentralized social media account!](https://mstdn.io/@okTurtles)

Also, the recently merged PR #61 needs to be applied to [the blog repo as well](https://github.com/okTurtles/blog.okturtles.org).

### Solution

1. Add the [Mastodon SVG icon](https://gist.github.com/SpaceOyster/c3d6d573ec375f91b0c91756ceeeb88d) (here's [more](https://iconscout.com/icons/mastodon) if needed) to this repo and the blog repo as PRs.
2. Update the blog repo with the updated Twitter icon too

**Comment by SebinSong** [comment]
@taoeffect The link to the blog repo is apparently broken, fyi.

**Comment by taoeffect** [comment]
@SebinSong What do you mean?

**Comment by taoeffect** [comment]
@SebinSong Sorry! You should be able to see it now!
